### ISSUE TITLE
ユーザメールアドレス関連APIが未完成

### ISSUE THREAD

**Issue by murata0531** [ecc-proken/GawdiBoard-backend#114]
【今後の開発・運用メンバーへのお願い】
`ユーザーメールアドレス登録API`、`ユーザーメールアドレス編集API` が未完成なので対応お願いします
ファイルパス -> `app/Http/Controllers/UserController.php`
対応完了次第このissueを閉じてください

**Comment by akisu1016** [comment]
本番環境に移す際に問題があって保留していますが、一応ロジックはできているみたいなので大丈夫だと思います。

**Comment by murata0531** [comment]
> 本番環境に移す際に問題があって保留していますが、一応ロジックはできているみたいなので大丈夫だと思います。

**Comment by murata0531** [comment]
対応済
