### ISSUE TITLE
formatterの説明について

### ISSUE THREAD

**Issue by murata0531** [ecc-proken/GawdiBoard-backend#52]
formatterを起動した際に ` /database/seeders/` や `/resources/` に変更があったのでメンバー間でformatterの共有ができてなさそう
formatterでコードを整形するための説明やドキュメントがない？

開発ドキュメントなどを作成してメンバー間で共有する仕組みを作った方が良さそう

**Comment by shibayaman** [comment]
実は[READMEのはじめ方](https://github.com/ecc-proken/GawdiBoard-backend#%E5%A7%8B%E3%82%81%E6%96%B9)の部分にprecommitでフォーマッターを走らせるためのコマンドが含まれていて、その通りに開発を始めてもらうとコミットするたびに変更したファイルが整形されるはず。

確かに説明は不足してると思うので、READMEを充実させるかCONTRIBUTING.mdとかを書くといいかなと思ってる。

開発プロセスに変更がある時はREADMEに書く + Slackで通知するって感じでやってるのだけど、見てない人や見たけど対応してない人がいてもわからないのは問題かも。解決案求む。
(対応済みの人はSlackで特定のリアクションを押すようにするとか？

**Comment by murata0531** [comment]
もしかして : ` composer format ` コマンドが不足している?
githooksコマンドは記載されているが ` composer format `  を実行していなかったためコードが整形されなかった可能性がある

開発プロセスをREADMEに記載するか ` 開発説明書 ` などのドキュメントを資料一覧に追加してもよさそう

**Comment by murata0531** [comment]
swagger 関連の整形が自動で整形されなかった
何かの制約があるのかな?
なければ開発フローを書くべきかな

**Comment by murata0531** [comment]
とりあえず開発フローに明記する形で解決
